version: '3'
services:
  app:
    image: maslow123/keuanganku-client
    container_name: app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 3030:3030
    restart: on-failure
    env_file:
      - .env
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    networks:
      - keuanganku
networks:
  keuanganku:
    driver: bridge